export const metadata = {
    title: 'about my first next js app',
    description: 'Generated by create next app',
  }
  const AboutLayout = ({children})=>{
   
    return (
        <div>
        <h1>this is the about layout</h1>
        {children}
        </div>
    );
};
export default AboutLayout